receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true

  filelog:
    include_file_path: true
    poll_interval: 500ms
    include:
      - /var/log/syslog
    operators:
      - type: time_parser
        parse_from: attributes.time
        layout: '%Y-%m-%dT%H:%M:%S%z'

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s

connectors:
  datadog/connector: {}

exporters:
  datadog/exporter:
    api:
      key: <YOUR_DD_API_KEY>

service:
  pipelines:
    metrics:
      receivers: [datadog/connector, hostmetrics]
      processors: [batch]
      exporters: [datadog/exporter]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/connector, datadog/exporter]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/exporter]
